"""Test bodies, including the four shapes of Section 3.5.

    We present four examples of increasing nonconvexity.  The lightcurves were
    generated by: 1, an irregular shape (tilted to produce interesting
    lightcurves); 2, a shape based on the radar images of Asteroid Castalia
    (Hudson and Ostro 1994); 3, a peanut-shaped object) to represent a
    strongly nonconvex yet regular shape); and 4, a binary object.

The originals are not published numerically, so the bodies here are
*reconstructions in the same spirit*: each reproduces the qualitative feature
the paper needed it for (mild irregularity, a bilobed radar-style body, a deep
regular waist, and two detached components).  They are built on the octant
triangulation of Appendix A, so the facet count is always ``8 N^2``.
"""

from __future__ import annotations

from collections.abc import Callable

import numpy as np

from .geometry import rot_y, rot_z, unit_to_spherical
from .mesh import Polyhedron
from .sphharm import design_matrix
from .triangulation import octant_triangulation

__all__ = [
    "sphere",
    "ellipsoid",
    "radial_body",
    "gaussian_random_sphere",
    "irregular_shape",
    "castalia_like",
    "peanut",
    "binary",
    "paper_shape",
    "PAPER_SHAPE_NAMES",
]


def sphere(radius: float = 1.0, n_rows: int = 8) -> Polyhedron:
    """Unit-normal sphere from the octant triangulation."""
    s = octant_triangulation(n_rows)
    return Polyhedron(s.vertices * float(radius), s.facets)


def ellipsoid(a: float, b: float, c: float, n_rows: int = 8) -> Polyhedron:
    """Triaxial ellipsoid with semi-axes ``a``, ``b``, ``c``.

    Section 3.1 uses "the facet normals of a sphere or a triaxial ellipsoid
    triangulated in the standard manner", and Section 3.2 suggests "a suitable
    triaxial ellipsoid" as the initial guess for the coefficients ``a_lm``.
    """
    s = octant_triangulation(n_rows)
    return Polyhedron(s.vertices * np.array([a, b, c], dtype=float), s.facets)


def radial_body(
    radius: Callable[[np.ndarray, np.ndarray], np.ndarray], n_rows: int = 8
) -> Polyhedron:
    """Star-shaped body from a radial function ``r(theta, phi)``.

    Parameters
    ----------
    radius:
        Callable mapping polar angle and azimuth (both ``(V,)`` arrays, in
        radians) to radii.
    n_rows:
        ``N`` of the octant triangulation, giving ``8 N^2`` facets.

    Returns
    -------
    Polyhedron
    """
    s = octant_triangulation(n_rows)
    theta, phi = unit_to_spherical(s.vertices)
    r = np.asarray(radius(theta, phi), dtype=float)
    if r.shape != theta.shape:
        raise ValueError("radius() must return one value per vertex")
    if np.any(r <= 0):
        raise ValueError("radius() must be strictly positive")
    return Polyhedron(s.vertices * r[:, None], s.facets)


def gaussian_random_sphere(
    sigma: float = 0.2,
    nu: float = 3.0,
    lmax: int = 6,
    n_rows: int = 8,
    seed: int | None = 0,
) -> Polyhedron:
    """A Gaussian random sphere (Muinonen 1998).

    The paper repeatedly points at this family - Muinonen and Lagerros (1998)
    "aims to give an idea of the extremity and general class of the nonconvex
    shape by employing Gaussian random spheres", and Section 2 plans "a large
    sample of different shapes (especially Gaussian ones)".

    The radius is log-normal,
    ``r = a exp(s(theta, phi)) / sqrt(1 + sigma^2)`` with ``s`` a zero-mean
    Gaussian field of variance ``ln(1 + sigma^2)`` expanded in spherical
    harmonics with a power-law spectrum ``c_l ~ (l + 1)^-nu``.

    Parameters
    ----------
    sigma:
        Relative standard deviation of the radius.
    nu:
        Power-law index of the angular power spectrum; larger means smoother.
    lmax:
        Truncation degree of the random field.
    n_rows, seed:
        Triangulation density and random seed.

    Returns
    -------
    Polyhedron
    """
    if sigma <= 0:
        raise ValueError("sigma must be positive")
    s = octant_triangulation(n_rows)
    theta, phi = unit_to_spherical(s.vertices)
    rng = np.random.default_rng(seed)

    var = np.log(1.0 + sigma**2)
    degrees = np.array([l for l in range(lmax + 1) for _ in range(-l, l + 1)])
    weights = np.where(degrees == 0, 0.0, (degrees + 1.0) ** (-nu))
    weights *= var / weights.sum()
    coeffs = rng.normal(scale=np.sqrt(weights))

    field = design_matrix(lmax, theta, phi) @ coeffs
    # Normalise so the *sample* has the requested statistics regardless of the
    # basis normalisation, then apply the log-normal correction.
    field *= np.sqrt(var) / max(field.std(), 1e-12)
    r = np.exp(field - 0.5 * var)
    return Polyhedron(s.vertices * r[:, None], s.facets)


def irregular_shape(n_rows: int = 8, tilt_deg: float = 25.0) -> Polyhedron:
    """Paper shape 1 - "an irregular shape (tilted to produce interesting
    lightcurves)".

    A mildly lumpy, almost-convex body: a triaxial ellipsoid modulated by a few
    low-degree harmonics, then tilted with respect to the rotation axis so that
    the lightcurves are not symmetric.

    Parameters
    ----------
    n_rows:
        Triangulation density.
    tilt_deg:
        Angle between the body's long axis and the equatorial plane.
    """
    axes = np.array([1.0, 0.72, 0.62])

    def radius(theta: np.ndarray, phi: np.ndarray) -> np.ndarray:
        d = design_matrix(3, theta, phi)
        bumps = 0.16 * d[:, 5] - 0.20 * d[:, 8] + 0.14 * d[:, 12] - 0.11 * d[:, 3]
        return 1.0 + bumps

    s = octant_triangulation(n_rows)
    theta, phi = unit_to_spherical(s.vertices)
    verts = s.vertices * axes * radius(theta, phi)[:, None]
    body = Polyhedron(verts, s.facets).centered()
    return body.rotated(rot_z(np.radians(20.0)) @ rot_y(np.radians(tilt_deg)))


def castalia_like(n_rows: int = 9) -> Polyhedron:
    """Paper shape 2 - "a shape based on the radar images of Asteroid
    Castalia (Hudson and Ostro 1994)".

    Castalia is the archetypal bilobed contact binary: two roughly equal
    ellipsoidal lobes joined at a narrow neck.  This reconstruction takes the
    union of two overlapping ellipsoids offset along ``x``, evaluated as a
    star-shaped radial function about the common centre, and adds a little
    asymmetry so the two lobes are not identical.

    Notes
    -----
    Figure 5 of the paper shows the nonconvex inversion result for this shape,
    obtained "using the function (15) and the vertex directions of a
    triangulated sphere"; :mod:`lcinv.nonconvex` reproduces that setup.
    """
    lobes = (
        (np.array([0.46, 0.0, 0.0]), np.array([0.62, 0.50, 0.45])),
        (np.array([-0.44, 0.0, 0.0]), np.array([0.58, 0.44, 0.40])),
    )

    def radius(theta: np.ndarray, phi: np.ndarray) -> np.ndarray:
        st = np.sin(theta)
        u = np.stack([st * np.cos(phi), st * np.sin(phi), np.cos(theta)], axis=1)
        best = np.zeros(len(u))
        for centre, semi in lobes:
            # Largest t with |(t u - c)/s| = 1: a quadratic in t.
            a = ((u / semi) ** 2).sum(axis=1)
            b = -2.0 * ((u * centre) / semi**2).sum(axis=1)
            c = ((centre / semi) ** 2).sum() - 1.0
            disc = b**2 - 4.0 * a * c
            t = np.where(disc > 0, (-b + np.sqrt(np.maximum(disc, 0.0))) / (2.0 * a), 0.0)
            best = np.maximum(best, t)
        return best

    return radial_body(radius, n_rows).centered()


def peanut(n_rows: int = 9, waist: float = 0.45, width: float = 0.42) -> Polyhedron:
    """Paper shape 3 - "a peanut-shaped object [...] to represent a strongly
    nonconvex yet regular shape".

    A prolate body with a deep, symmetric equatorial waist pinched about the
    ``x = 0`` plane.

    Parameters
    ----------
    n_rows:
        Triangulation density.
    waist:
        Fractional depth of the pinch, ``0`` for no waist and ``1`` for a full
        cut.  Section 3.5 notes that even for this body "the regularity and
        symmetricity [...] seem to contribute to the lightcurve much more than
        the otherwise large concavity in the middle".
    width:
        Width of the pinch along the long axis.
    """
    if not 0.0 <= waist < 1.0:
        raise ValueError("waist must lie in [0, 1)")
    axes = np.array([1.0, 0.55, 0.52])

    def radius(theta: np.ndarray, phi: np.ndarray) -> np.ndarray:
        st = np.sin(theta)
        x = st * np.cos(phi)  # direction cosine along the long axis
        return 1.0 - waist * np.exp(-((x / width) ** 2))

    s = octant_triangulation(n_rows)
    theta, phi = unit_to_spherical(s.vertices)
    return Polyhedron(s.vertices * axes * radius(theta, phi)[:, None], s.facets)


def binary(
    n_rows: int = 7,
    separation: float = 2.6,
    size_ratio: float = 0.62,
) -> Polyhedron:
    """Paper shape 4 - "a binary object", as two detached components.

    Section 2 notes that "triangulation can be applied separately to each
    object of a group; thus, e.g., binary objects can be handled with the same
    code".  The two components are returned as a single
    :class:`~lcinv.mesh.Polyhedron` with two disconnected closed surfaces;
    :class:`~lcinv.raytracer.RayTracer` searches all vertices when building
    local blockers, so the components correctly shadow and eclipse each other.

    Parameters
    ----------
    n_rows:
        Triangulation density per component.
    separation:
        Centre-to-centre distance in units of the primary's long semi-axis.
    size_ratio:
        Secondary/primary size ratio.

    Returns
    -------
    Polyhedron
        Two components, centred on the system's centre of volume.
    """
    primary = ellipsoid(1.0, 0.85, 0.80, n_rows)
    secondary = ellipsoid(
        size_ratio, size_ratio * 0.88, size_ratio * 0.82, n_rows
    ).rotated(rot_z(np.radians(35.0)))

    frac = 1.0 / (1.0 + size_ratio**3)  # split the offset by volume
    a = primary.translated([-separation * (1.0 - frac), 0.0, 0.0])
    b = secondary.translated([separation * frac, 0.0, 0.0])
    verts = np.vstack([a.vertices, b.vertices])
    facets = np.vstack([a.facets, b.facets + a.n_vertices])
    return Polyhedron(verts, facets).centered()


#: Names accepted by :func:`paper_shape`, in the paper's own order.
PAPER_SHAPE_NAMES = ("irregular", "castalia", "peanut", "binary")


def paper_shape(which: int | str, n_rows: int | None = None) -> Polyhedron:
    """One of the four Section 3.5 test bodies.

    Parameters
    ----------
    which:
        ``1``-``4``, or one of :data:`PAPER_SHAPE_NAMES`.
    n_rows:
        Optional triangulation density override.

    Returns
    -------
    Polyhedron
    """
    if isinstance(which, str):
        key = which.lower()
        if key not in PAPER_SHAPE_NAMES:
            raise ValueError(f"unknown shape {which!r}; expected one of {PAPER_SHAPE_NAMES}")
        index = PAPER_SHAPE_NAMES.index(key) + 1
    else:
        index = int(which)
        if not 1 <= index <= 4:
            raise ValueError("shape number must be 1, 2, 3 or 4")
    builders = (irregular_shape, castalia_like, peanut, binary)
    builder = builders[index - 1]
    return builder() if n_rows is None else builder(n_rows=n_rows)
